config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :projects do
    resources :tasks do
    end
  end

  resources :projects do
    resources :comments do
    end
  end

  authenticated :user do
      root "projects#index", as: "authenticated_root"
  end

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  has_many :comments
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_project
  before_action :set_comment, only: [:destroy]

  def index
    @comments = set_project.comments.all
  end

  def new
    @comment = set_project.comments.new
  end

  def create
     @comment = set_project.comments.create(comment_params)
     redirect_to @project
  end

  def destroy
    @comment.destroy
    redirect_to @project
  end

  private

  def set_project
      @project = Project.find(params[:project_id])
  end

  def set_comment
    @comment = @project.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :attachment)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end

   def correct_user
     @project = current_user.projects.find_by(id: params[:id])
     redirect_to projects_path, notice:'Not authorized to edit this project' if @project.nil?
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tasks = set_project.tasks.all
  end

  def show

  end

  def new
    @task = set_project.tasks.new
  end

  def edit
  end

  def create
    @task = set_project.tasks.create(task_params)
    redirect_to @project
  end

  def update
    if @task.update(task_params)
      redirect_to project_task_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end

  end

  def complete
        @task.update_attribute(:completed, True)
        redirect_to @project, notice: "Task completed"
    end

  def destroy
    if @task.destroy
            flash[:success] = "Project task was deleted"
        else
            flash[:error] = "Project task could not be deleted"
        end
    redirect_to @project
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :deadline, :priority, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/new.html.erb
<%= form_for(([@project, @comment]), multipart: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @commentt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :body %><br>
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
<br>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to MyApp!</h1>
<p>Please <%= link_to 'Login', new_user_session_path %> or
  <%= link_to 'Signup', new_user_registration_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MyApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% end %>
  <%= yield %>

</body>

</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>
<% if @projects.exists? %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>
    <strong>Please, add your first project</strong>
  </p>
<% end %>

<br>

<p>
  <%= link_to 'New Project', new_project_path %>
</p>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


 <h1><%= @project.name %></h1>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
<p>
   <%= link_to 'Create Task', new_project_task_path(@project) %>
</p>

<hr>
<h2>Comments:</h2>
<% if @project.comments.exists? %>
  <% @project.comments.each do |comment| %>
    <p><%= comment.body %></p>
    <% if comment.attachment? %>
      <p><%= link_to "Download File", comment.attachment_url, target: '_blank' %></p>
    <% end %>
    <p><%= link_to 'Delete', project_comment_path(@project, comment), method: :delete %></p>
  <% end %>
<% else %>
  <em>Currently no comments</em><br><br>
<% end %>
<%= link_to 'Add Comment', new_project_comment_path(@project) %>
<br>
<br>
<hr>

<h2>Listing tasks:</h2>
<% if @project.tasks.exists? %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>Priority</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project.tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.deadline %></td>
        <td><%= task.priority %></td>
        <td><%= task.completed %></td>
        <td><%= link_to 'Show', project_task_path(@project, task) %></td>
        <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
        <td><%= link_to 'Destroy', project_task_path(@project, task), method: :delete  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <em>Add your first task</em>
<% end %>
<br>
<br>

<%= link_to 'New Task', new_project_task_path(@project) %>

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select(:priority, [['High'], ['Medium'], ['Low']]) %>


  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', project_task_path(@project, @task) %> |
<%= link_to 'Back', project_path(@project) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>Priority</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.deadline %></td>
        <td><%= task.priority %></td>
        <td><%= task.completed %></td>
        <td><%= link_to 'Show', project_task_path(@project, task) %></td>
        <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
        <td><%= link_to 'Destroy' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%=@task.deadline %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
<%= link_to 'Back', project_path(@project) %>